version: '3'

services:
  #Backend Services
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      mgmt0:
        aliases:
          - es01
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      mgmt0:
        aliases:
          - kibana

  mqtt-broker:
    container_name: MQTT-Broker
    image: eclipse-mosquitto
    hostname: mosquitto
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "1883:1883"
    volumes:
      - ./Backend/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt-broker:
        aliases:
          - mqtt


  #HTTP
  http-server0:
    container_name: http-server
    build: ./http-server/
    restart: always
    depends_on:
      - es01
    networks:
      http-proxy-to-server:
        aliases:
          - server
      mgmt0:
  http-client0:
    container_name: http-clients
    build: ./http-client/
    restart: always
    depends_on:
      - es01
    networks:
      http-proxy-from-client:
      mgmt0:

  http-stunnel-client0:
    container_name: Stunnel-HTTP-Client
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_client.conf:/etc/stunnel/stunnel.conf
    networks:
      http-proxy-backend:
        aliases:
          - stunnelclient
      http-proxy-from-client:
        aliases:
          - http
    command: bash -c "stunnel4 && tail -f /dev/null"
  http-stunnel-server0:
    container_name: Stunnel-HTTP-Server
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_server.conf:/etc/stunnel/stunnel.conf
    networks:
      http-proxy-backend:
        aliases:
          - stunnelserver
      http-proxy-to-server:
    command: bash -c "stunnel4 && tail -f /dev/null"

  #MQTT
  #MQTT Client
  mqtt-client:
    container_name: mqtt-client
    build: ./mqtt-client/
    restart: always
    depends_on:
      - mqtt-broker
      - es01
    networks:
      mqtt-client-to-broker:
      mgmt0:
  #MQTT Server
  mqtt-server:
    container_name: mqtt-server
    build: ./mqtt-server/
    restart: always
    depends_on:
      - mqtt-broker
      - es01
    networks:
      mqtt-server-to-broker:
      mgmt0:

  #MQTT Client Stunnel Instance
  mqtt-from-client-to-backend-stunnel:
    container_name: Stunnel-MQTT-from-client-to-backend
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_client.conf:/etc/stunnel/stunnel.conf
    networks:
      mqtt-client-backend:
      mqtt-client-to-broker:
        aliases:
          - mqtt
    command: bash -c "stunnel4 && tail -f /dev/null"
  mqtt-client-to-broker-stunnel:
    container_name: Stunnel-MQTT-from-Client-to-Broker
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_server.conf:/etc/stunnel/stunnel.conf
    networks:
      mqtt-client-backend:
        aliases:
          - stunnelserver
      mqtt-broker:
    command: bash -c "stunnel4 && tail -f /dev/null"



  #MQTT Server Stunnel Instance
  mqtt-from-server-to-backend-stunnel:
    container_name: Stunnel-MQTT-from-Server-to-backend
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_client.conf:/etc/stunnel/stunnel.conf
    networks:
      mqtt-server-backend:
      mqtt-server-to-broker:
        aliases:
          - mqtt
    command: bash -c "stunnel4 && tail -f /dev/null"
  mqtt-server-to-broker-stunnel:
    container_name: Stunnel-MQTT-from-Server-to-Broker
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_server.conf:/etc/stunnel/stunnel.conf
    networks:
      mqtt-server-backend:
        aliases:
          - stunnelserver
      mqtt-broker:
    command: bash -c "stunnel4 && tail -f /dev/null"

  stats:
    container_name: stats
    build: ./docker-stats/
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - es01
    networks:
      mgmt0:

networks:
  #managment network
  mgmt0:


  #HTTP
  #proxy backend (between the stunnel instances)
  http-proxy-backend:
  #proxy between the client and stunnel client instance
  http-proxy-from-client:
  #proxy between the server and stunnel server instance
  http-proxy-to-server:

  #MQTT
  #proxy between the client stunnel instnaces
  mqtt-client-backend:
  #proxy between the server stunnel instances
  mqtt-server-backend:
  #proxy between the client and client stunnel instance
  mqtt-client-to-broker:
  #proxy between the server and server stunnel instance
  mqtt-server-to-broker:
  #mqtt broker network
  mqtt-broker:

volumes:
  data01:
    driver: local
