version: '3'

services:
  #Backend Services
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      mgmt0:
        aliases:
          - es01
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      mgmt0:
        aliases:
          - kibana

  mqtt-broker:
    container_name: MQTT-Broker
    image: eclipse-mosquitto
    hostname: mosquitto
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "1883:1883"
    volumes:
      - ./Backend/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt-broker:
        aliases:
          - mqtt
  sys-mqtt-to-es:
    build: ./sys-mqtt-to-es/
    container_name: System-to-Elastic
    restart: always
    depends_on:
      - es01
      - mqtt-broker
      - kibana
    networks:
      mqtt-broker:
      mgmt0:

  #HTTP
  http-server0:
    container_name: HTTP-Server
    build: ./http-server/
    restart: always
    depends_on:
      - es01
    networks:
      http-proxy-to-server:
        aliases:
          - server
      mgmt0:
  http-client0:
    container_name: HTTP-Client
    build: ./http-client/
    restart: always
    depends_on:
      - es01
    networks:
      http-proxy-from-client:
      mgmt0:

  http-stunnel-client0:
    container_name: Stunnel-HTTP-Client
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_client.conf:/etc/stunnel/stunnel.conf
    networks:
      http-proxy-backend:
        aliases:
          - stunnelclient
      http-proxy-from-client:
        aliases:
          - http
    command: bash -c "stunnel4 && tail -f /dev/null"
  http-stunnel-server0:
    container_name: Stunnel-HTTP-Server
    build: ./stunnel/
    restart: always
    volumes:
      - ./stunnel_configs/stunnel4:/etc/default/stunnel4
      - ./stunnel_configs/psk.txt:/etc/stunnel/psk.txt
      - ./stunnel_configs/stunnel_server.conf:/etc/stunnel/stunnel.conf
    networks:
      http-proxy-backend:
        aliases:
          - stunnelserver
      http-proxy-to-server:
    command: bash -c "stunnel4 && tail -f /dev/null"


  mqtt-client0:
    container_name: MQTT-Client
    build: ./mqtt-client/
    restart: always
    depends_on:
      - mqtt-broker
      - es01
    networks:
      mgmt0:
  mqtt-server0:
    container_name: MQTT-Server
    build: ./mqtt-server/
    restart: always
    depends_on:
      - mqtt-broker
      - es01
    networks:
      mgmt0:

networks:
  #managment network
  mgmt0:


  #HTTP
  #proxy backend (between the stunnel instances)
  http-proxy-backend:
  #proxy between the client and stunnel client instance
  http-proxy-from-client:
  #proxy between the server and stunnel server instance
  http-proxy-to-server:

  #MQTT
  #proxy between the client stunnel instnaces
  mqtt-client-backend:
  #proxy between the server stunnel instances
  mqtt-server-backend:
  #proxy between the client and client stunnel instance
  mqtt-client-to-broker:
  #proxy between the server and server stunnel instance
  mqtt-server-to-broker:
  #mqtt broker network
  mqtt-broker:

volumes:
  data01:
    driver: local
