version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      mgmt0:
        aliases:
          - es01
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      mgmt0:
        aliases:
          - kibana

  mqtt-proxy-client:
    build: ./mqtt-proxy/
    restart: always
    cap_add:
       - NET_ADMIN
    volumes:
      - ./wireguard-configs/wg0-client.conf:/etc/wireguard/wg0.conf
      - ./nginx-configs/client.conf:/etc/nginx/nginx.conf
    networks:
      mqtt-client-backbone:
        aliases:
           - wgclient
      mqtt-client-proxy:
        aliases:
           - mqtt
    command: bash -c "nginx && wg-quick up wg0 && tail -f /dev/null"

  mqtt-client-broker-proxy:
    build: ./mqtt-proxy/
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wireguard-configs/wg0-server.conf:/etc/wireguard/wg0.conf
      - ./nginx-configs/server.conf:/etc/nginx/nginx.conf
    networks:
      mqtt-client-backbone:
        aliases:
          - wgserver
      mqtt-client-broker-proxy:

    command: bash -c "nginx && wg-quick up wg0 && tail -f /dev/null"

  mqtt-server-broker-proxy:
    build: ./mqtt-proxy/
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wireguard-configs/wg0-server.conf:/etc/wireguard/wg0.conf
      - ./nginx-configs/server.conf:/etc/nginx/nginx.conf
    networks:
      mqtt-server-backbone:
        aliases:
          - wgserver
      mqtt-server-broker-proxy:
    command: bash -c "nginx && wg-quick up wg0 && tail -f /dev/null"

  mqtt-proxy-server:
    build: ./mqtt-proxy/
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wireguard-configs/wg0-client.conf:/etc/wireguard/wg0.conf
      - ./nginx-configs/client.conf:/etc/nginx/nginx.conf
    networks:
      mqtt-server-backbone:
        aliases:
          - wgclient
      mqtt-server-proxy:
        aliases:
          - mqtt
    command: bash -c "nginx && wg-quick up wg0 && tail -f /dev/null"


  mqtt-broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "1883:1883"
    volumes:
      - ./Backend/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      mqtt-server-broker-proxy:
        aliases:
          - mqtt
      mqtt-client-broker-proxy:
        aliases:
          - mqtt
      mgmt0:
        aliases:
          - mqtt
  sys-mqtt-to-es:
    build: ./sys-mqtt-to-es/
    restart: always
    depends_on:
      - es01
      - mqtt-broker
      - kibana
    networks:
      mgmt0:

  mqtt-client0:
    build: ./mqtt-client/
    restart: always
    depends_on:
      - mqtt-broker
      - es01
    networks:
      mqtt-client-proxy:
      mgmt0:
  mqtt-server0:
    build: ./mqtt-server/
    restart: always
    depends_on:
      - mqtt-broker
      - es01
    networks:
      mqtt-server-proxy:
      mgmt0:

networks:
  mgmt0:
  mqtt-client-proxy:
  mqtt-client-backbone:
  mqtt-client-broker-proxy:
  mqtt-server-broker-proxy:
  mqtt-server-backbone:
  mqtt-server-proxy:

volumes:
  data01:
    driver: local
